=== MohawkMEDIC/client-registry/MARC.HI.EHRS.CR.Messaging.HAPI/Configuration/marc.hi.ehrs.cr.messaging.hl7.xsd
<?xml version="1.0" encoding="utf-8"?>

<!--

  Copyright 2012-2013 Mohawk College of Applied Arts and Technology
  
  Licensed under the Apache License, Version 2.0 (the "License"); you 
  may not use this file except in compliance with the License. You may 
  obtain a copy of the License at 
  
  http://www.apache.org/licenses/LICENSE-2.0 
  
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the 
  License for the specific language governing permissions and limitations under 
  the License.
  
  User: fyfej
  Date: 21-8-2012


-->

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:simpleType name="attributeName">
    <xs:restriction base="xs:string">
      <xs:enumeration value="x509.cert"/>
      <xs:enumeration value="x509.store"/>
      <xs:enumeration value="x509.location"/>
      <xs:enumeration value="client.cert"/>
      <xs:enumeration value="client.store"/>
      <xs:enumeration value="client.location"/>

    </xs:restriction>
  </xs:simpleType>
  <xs:element name="marc.hi.ehrs.cr.messaging.hl7">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="services">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="service" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" maxOccurs="unbounded" name="attribute">
                      <xs:complexType>
                        <xs:attribute name="name" type="attributeName" use="required"/>
                        <xs:attribute name="value" type="xs:string"/>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="1" maxOccurs="unbounded" name="handler">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="message" maxOccurs="unbounded">
                            <xs:complexType>
                              <xs:attribute name="name" type="xs:string" use="required" />
                              <xs:attribute name="isQuery" type="xs:boolean"/>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                        <xs:attribute name="type" type="xs:string" use="required" />
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                  <xs:attribute name="name" type="xs:string" use="required" />
                  <xs:attribute name="address" type="xs:string" use="required" />
                  <xs:attribute name="timeout" type="xs:time"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== MohawkMEDIC/client-registry/MARC.HI.EHRS.CR.Presentation/HL7Config.xml
<marc.hi.ehrs.cr.messaging.hl7 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file://./Configuration/marc.hi.ehrs.cr.messaging.hl7.xsd">
  <services>
    <!--<service name="TCP Listener" address="tcp://0.0.0.0:1027">
        <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.PixHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
          <message name="QBP^Q23"/>
        </handler>
        <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.PdqHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
          <message name="QBP^Q22"/>
        </handler>
        <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.NotSupportedHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
          <message name="*"/>
        </handler>
      </service>-->
    <!--<service name="SLLP Listener" timeout="00:00:30" address="sllp://0.0.0.0:2200">
        <attribute name="x509.cert" value="555A48A9DED421A8E1CF40CEDADD6732782850DF"/>
        <attribute name="x509.store" value="My"/>
--><!--        <attribute name="client.castore" value="Root"/>
        <attribute name="client.cacert" value="8fde87cfea569e65a3c44ea2dcc1af3ca5bd12c1"/>--><!--
        <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.PixHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
          <message name="QBP^Q23" isQuery="true"/>
          <message name="ADT^A01"/>
          <message name="ADT^A04"/>
          <message name="ADT^A05"/>
          <message name="ADT^A08"/>
        </handler>
        <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.PdqHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
          <message name="QBP^Q22" isQuery="true"/>
        </handler>
        <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.NotSupportedHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
          <message name="*"/>
        </handler>
      </service>-->
    <service name="LLP Listener" timeout="00:00:30" address="llp://0.0.0.0:2200">
      <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.PixHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
        <message name="QBP^Q23" isQuery="true"/>
        <message name="ADT^A01"/>
        <message name="ADT^A04"/>
        <message name="ADT^A05"/>
        <message name="ADT^A08"/>
      </handler>
      <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.PdqHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
        <message name="QBP^Q22" isQuery="true"/>
      </handler>
      <handler type="MARC.HI.EHRS.CR.Messaging.PixPdqv2.NotSupportedHandler, MARC.HI.EHRS.CR.Messaging.PixPdqv2, Version=1.0.0.0">
        <message name="*"/>
      </handler>
    </service>
  </services>
</marc.hi.ehrs.cr.messaging.hl7>
